version: "3"
services:
  server-prod:
    build: "."
    ports:
      - "80:3000"
      - "443:3001"
    environment:
      NODE_ENV: "production"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  server-dev:
    build: "."
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
