version: "3"
services:
  server-prod:
    build: "."
    ports:
      - "80:3000"
    environment:
      NODE_ENV: "production"
    volumes:
      - /etc/letsencrypt/live/wiki-test.johndyer.dev:/etc/letsencrypt/credentials
  server-dev:
    build:
      dockerfile: "Dockerfile.dev"
      context: "."
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
